---
title: "Temporal distribution of combined data set"
author: "Julie K. Sheard"
date: "12 May 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is the script to visualise the combined dataset

# Initial set-up

## Load packages
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
```

## Load data
```{r}
detections <- read.csv("C:/Users/julie/Documents/Projects/Occupancy/data/detections_decades.csv", sep=",", header=TRUE)

```

#Plot occurrence records across time periods for each dataset

```{r}
#Summarise number of detections in each decade
totals <- detections %>%
    group_by(tp_year) %>%
    summarize(total = sum(detections))

#Ten year time periods
png("Plot3.png", width = 800, height = 600)
ggplot(data=detections, aes(x=tp_year, y=detections, fill=origin)) +
  geom_bar(stat="identity") +
  geom_text(aes(tp_year, total + 80, label = total, fill = NULL), size=6, data = totals) +
  theme_classic() +
  theme(text = element_text(size=25),
        axis.text.x = element_text(angle=75, hjust=1),
        legend.title = element_blank(),
        legend.position="bottom") + 
  scale_fill_manual(values = c("#FDE825", "#9FDA3A", "#49C16D", "#21A187", "#287F8E", "#365C8D", "#44317D")) +
  xlab("Decade") +
 ylab("Detections")
dev.off()
```

